config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :posts do
    resources :comments, except: [:show, :index]
  end
  resources :users, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :sort_by_created_desc, ->{order created_at: :desc}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true,
    length: {maximum: Settings.post_title_max_length}
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true,
    length: {maximum: Settings.first_name_max_length}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_post
  before_action :load_comment, except: [:new, :create]
  before_action :authenticate_user!
  before_action :correct_user, except: [:new, :create]

  def new; end

  def create
    @comment = @post.comments.build comment_params
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = t "create_successfully"
      redirect_to post_path @post
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update_attributes comment_params
    flash[:success] = t "update_successfully"
    redirect_to post_path @post
    else
      render :edit
    end
  end

  def destroy
    if @comment.destroy
      flash[:success] = t "delete_successfully"
    else
      flash.now[:danger] = t "error_message"
    end
    redirect_to post_path @post
  end

  private

  def comment_params
    params.require(:comment).permit :content, :post_id, :user_id
  end

  def load_post
    @post = Post.find_by id: params[:post_id]
    return if @post
    render file: "public/404.html", status: :not_found, layout: false
  end

  def load_comment
    @comment = Comment.find_by id: params[:id]
    return if @comment
    render file: "public/404.html", status: :not_found, layout: false
  end

  def correct_user
    if @comment.user_id != current_user.id
      flash[:danger] = t "access_denied"
      redirect_to root_url
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_post, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :correct_user, only: [:edit, :update]

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build post_params

    if @post.save
      flash[:success] = t "create_successfully"
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @posts = Post.sort_by_created_desc.paginate page: params[:page],
      per_page: Settings.number_of_posts_per_page
  end

  def show; end

  def destroy
    if @post.destroy
      flash[:success] = t "delete_successfully"
    else
      flash[:danger] = t "error_message"
    end
    redirect_to posts_url
  end

  def update
    if @post.update_attributes post_params
      flash[:success] = t "update_successfully"
      redirect_to @post
    else
      render :edit
    end
  end

  def edit; end

  private

  def post_params
    params.require(:post).permit :title, :content
  end

  def load_post
    @post = Post.find_by id: params[:id]
    return if @post
    render file: "public/404.html", status: :not_found, layout: false
  end

  def correct_user
    if @post.user_id != current_user.id
      flash[:danger] = t "access_denied"
      redirect_to @post
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password,
      :password_confirmation, :first_name, :last_name, :phone])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:password,
      :password_confirmation, :first_name, :last_name, :phone])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show]

  def show; end

  def index
    @users = User.sort_by_created_desc.paginate page: params[:page],
      per_page: Settings.number_of_users_per_page
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user
    render file: "public/404.html", status: :not_found, layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = I18n.t(".base_title")
    page_title.blank? ? base_title : page_title + " | " + base_title
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><b> <%= comment.user.first_name + " " + comment.user.last_name%> </b>
- <%= distance_of_time_in_words(Time.now - comment.created_at) %>
 <%= t ".content_1" %>
<% if user_signed_in? && comment.user_id == current_user.id %>
  <%= link_to t(".edit"), edit_post_comment_path(comment.post, comment) %>
  - <%= link_to t(".delete"), post_comment_path(comment.post, comment),
  method: :delete, data: {confirm: t("delete_confirm_message")} %>
<% end %>
<br/>
<%= comment.content %>
<br/></p>

app/views/comments/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.input :content %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/comments/edit.html.erb
<% provide :title, t("edit_comment") %>

<h1><%= t ".content_1" %></h1>

<div class="col-md-6 col-md-offset-3">
  <%= simple_form_for([@post, @comment]) do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.input :content %>

  <%= f.submit t("update_btn"), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/comments/new.html.erb
<% provide :title, t("new_comment") %>
<% provide :button_text, t("create_btn") %>

<h1><%= t ".content_1" %></h1>
<%= render "form" %>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t("logo_in_word"), root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <ul class="nav navbar-nav navbar-left">
      <% if user_signed_in? %>
        <li><%= link_to t(".add_post_btn"), new_post_path %></li>
      <% end %>
      <li><%= link_to t(".users_btn"), users_path %></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <%= link_to "#" , class: "dropdown-toggle", data: {toggle:"dropdown"} do %>
          <%= current_user.first_name %> <b class="caret"></b> <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to t(".profile_btn"), current_user %></li>
            <li><%= link_to t(".setting_btn"), edit_user_registration_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to t(".sign_out_btn"), destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to t(".sign_in_btn"), new_user_session_path %></li>
        <li><%= link_to t(".signup_btn"), new_user_registration_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>
  <body>
    <%= render "layouts/header" %>

    <div class="container">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= simple_form_for @post do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.input :title, label: t("post_title_label") %>
  <%= f.input :content %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="post_content_display">
      <p> <%= distance_of_time_in_words(Time.now - post.created_at) %> </p>
      <p> <%= post.title %> </p>
      <p> <%= post.content %> </p>
      <div class="row">
        <div class="col-md-6", id="post_btns"> Like </div>
        <div class="col-md-6", id="post_btns">
          <%= link_to t(".comment"), post_path(post.id) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide :title, t("edit_post") %>
<% provide :button_text, t("update_btn") %>

<h1><%= t ".edit_post" %></h1>
<%= render "form" %>

app/views/posts/index.html.erb
<% provide :title, t("home") %>

<%= will_paginate %>

<% if @posts.size == 0 %>
  <h2><%= t ".content_1" %></h2>
<% else %>
  <%= render @posts %>
<% end %>

<%= will_paginate %>

app/views/posts/new.html.erb
<% provide :title, t("new_post") %>
<% provide :button_text, t("create_btn") %>

<h1><%= t ".add_new_post" %></h1>
<%= render "form" %>

app/views/posts/show.html.erb
<% provide :title, t("post_detail") %>

<div class="col-md-6 col-md-offset-3">
  <div class="post_content_display">
    <% if user_signed_in? && @post.user_id == current_user.id %>
      <%= link_to t(".edit"), edit_post_path(@post) %>
      <%= link_to t(".delete"), @post_path, method: :delete,
        data: {confirm: t("delete_confirm_message")} %>
    <% end %>
    <p> <%= distance_of_time_in_words(Time.now - @post.created_at) %> </p>
    <p> <%= @post.title %> </p>
    <p> <%= @post.content %> </p>
    <div class="row">
      <div class="col-md-6", id="post_btns"> Like </div>
      <div class="col-md-6", id="post_btns">
        <%= link_to t(".comment"), new_post_comment_path(@post) %>
      </div>
    </div>
    <hr>
  <%= render @post.comments %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t(:form_error_count, count: object.errors.size) %>
    </div>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td> <%= user.id %> </td>
  <td> <%= link_to user.first_name, user %> </td>
  <td> <%= user.last_name %> </td>
  <td> <%= user.email %> </td>
  <td> <%= user.phone %> </td>
</tr>

app/views/users/index.html.erb
<% provide :title, t("user_index") %>

<h1><%= t(".content_1") %></h1>

<% if @users.size == 0 %>
  <h2><%= t ".content_2" %></h2>
<% else %>
  <%= will_paginate %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th> <%= t ".tab_tit_id" %> </th>
        <th> <%= t ".tab_tit_fname" %> </th>
        <th> <%= t ".tab_tit_lname" %> </th>
        <th> <%= t ".tab_tit_email" %> </th>
        <th> <%= t ".tab_tit_phone" %> </th>
      </tr>
    </thead>
    <tbody>
      <%= render @users %>
    </tbody>
  </table>
  <%= will_paginate %>
<% end %>

app/views/users/show.html.erb
<% provide :title, @user.first_name %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= t(".content_1") %> <%= @user.first_name %>
        <%= @user.last_name %> <br/>
        <%= t(".content_2") %><%= @user.phone %>
      </h1>
    </section>
  </aside>
</div>